### ISSUE TITLE
grunt-lib-contrib is deprecated

### ISSUE THREAD

**Issue by sindresorhus** [somerandomdude/grunt-webp#11]
I noticed you have [grunt-lib-contrib](https://github.com/gruntjs/grunt-lib-contrib) as a dependency.

It's deprecated and I would recommend you switch to the extracted modules instead:
`stripPath` => [strip-path](https://github.com/sindresorhus/strip-path)
`minMaxInfo` => [maxmin](https://github.com/sindresorhus/maxmin)
`getNamespaceDeclaration` => [ticket](https://github.com/gruntjs/grunt-lib-contrib/issues/9)

**Comment by sindresorhus** [comment]
@somerandomdude ping

**Comment by somerandomdude** [comment]
Thanks for the reminder - I've dropped the ball on this. I'll work on fixing this during the weekend. Thanks dude.

**Comment by somerandomdude** [comment]
Finally got to this. Apologies for the delay.
