### ISSUE TITLE
Tag and publish to npm

### ISSUE THREAD

**Issue by paazmaya** [somerandomdude/grunt-webp#6]
Please make a minor release so that the `binpath` option becomes available via `npm install`.

**Comment by darcyclarke** [comment]
:+1: The NPM module is out-of-date. A quick version change in `package.json` and then an `npm update` would make my life a lot easier right now. Would love to use this task but the directory issue (which was solved here 706d7127f10dc297f21a4255146ea69e77108ad4) isn't reflected on NPM. /cc @somerandomdude

**Comment by somerandomdude** [comment]
Hey Darcy, I'm sorry I've been silent about this. I'll take care of it tonight.
 
On January 14, 2014 at 12:50:54 PM, Darcy Clarke (notifications@github.com) wrote:

 The NPM module is out-of-date. A quick version change in package.json and then an npm update would make my life a lot easier right now. Would love to use this task but the directory issue (which was solved here 706d712) isn't reflected on NPM. /cc @somerandomdude

**Comment by somerandomdude** [comment]
I'm on this. Promise. I swear I haven't forgotten about this.

**Comment by somerandomdude** [comment]
It should be up at 0.0.3. Apologies for the blackout on this.
